apiVersion: v1
kind: Service
metadata:
  name: my-java-application-service
spec:
  type: NodePort
  selector:
    app: my-java-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  

